[package]
name = "ldm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Accelerated download manager for Linux"

[[bin]]
name = "ldm"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ldm-core = { path = "../crates/ldm-core" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
log = "0.4"
env_logger = "0.11"
